name: build-android
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup ENV file
      run: |
        echo "${{secrets.JS_ENV_B64}}" | base64 --decode > .js.env
    - name: Install dependencies
      run: |
        yarn run setup:expo
        yarn run setup
    - name: Build APK
      run: |
        cd android
        chmod +x gradlew
        ./gradlew assembleFlaskRelease --no-daemon --max-workers 2
    - name: Archive artifacts
      uses: actions/upload-artifact@v4
      with:
        name: andorid-apk
        path: android/app/build/outputs/**/*.apk